cfg-version: 12
message: '&cYou have reached the edge of this world.'
round-border: false
debug-mode: false
whoosh-effect: true
portal-redirection: true
knock-back-dist: 3.0
timer-delay-ticks: 5
remount-delay-ticks: 10
dynmap-border-enabled: true
dynmap-border-layer-label: WorldBorder
dynmap-border-message: The border of the world.
dynmap-border-hideByDefault: false
dynmap-border-priority: 0
player-killed-bad-spawn: false
deny-enderpearl: true
fill-autosave-frequency: 30
bypass-list-uuids: []
fill-memory-tolerance: 500
prevent-block-place: true
prevent-mob-spawn: true
no-players-toggle: false
worlds:
  world:
    x: 15359.5
    z: 7999.5
    radiusX: 15360
    radiusZ: 8000
    wrapping: true
