  
  
update:
  # Seconds between updating Towny information on the dynmap.
  period: '300'
  
  
layer:
  
  # The name of the Towny layer on dynmap.
  name: Towny
  
  # Is the Towny layer hidden by default?
  hidebydefault: 'false'
  
  # Ordering priority in layer menu (low goes before high - default is 0)
  layerprio: '2'
  
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: '0'
visibility-by-town: true
visibility-by-nation: true
  
  
infowindow:
  
  # Format for town popup.
  town_info_window: <div class="infowindow"><span style="font-size:120%;">%nationstatus% <br /><span style="font-weight:bold;font-size:120%;">%regionname%</span><br /></span><br /> <span style="font-weight:bold;">Mayor:</span> <span style="font-weight:normal;">%playerowners%</span><br /><img src="https://minotar.net/bust/%playerowners%/64"><br /><span style="font-weight:bold;">&#x1F54A; Peaceful:</span> <span style="font-weight:normal;">%peaceful%</span><br /><span style="font-weight:bold;">&#x1F3A8; Culture:</span> <span style="font-weight:normal;">%culture%</span><br /><span style="font-weight:bold;">&#x1F4DC; Board:</span> <span style="font-weight:normal;">%board%</span><br /><span style="font-weight:bold;">&#x1F4B0; Bank:</span> <span style="font-weight:normal;">%bank%</span><br /><span style="font-weight:bold;">&#x1F4B0; Taxes:</span> <span style="font-weight:normal;">%tax%</span><br /> <span style="font-weight:bold;">&#x1F4B8; Upkeep:</span> <span style="font-weight:normal;">%upkeep%</span><br /> <span style="font-weight:bold;">&#x1F465; (%residentcount%)Residents:</span> <span style="font-weight:normal;">%playermembers%</span><br /><span style="font-weight:bold;">&#x1F300; PublicTP:</span> <span style="font-weight:normal;">%public%</span><br /><span style="font-weight:bold;">&#x1F3F0; Founded on:</span> <span style="font-weight:normal;">%founded%</span><br /><br/><span style="font-weight:bold;">&#x1F528; Resources:<span style="font-weight:normal;">%town_resources%</span><br/><span style="font-weight:bold;">Misc:<br /></span> <span style="font-weight:normal;">%flags%</span></div>
  
  # What is shown in the info window's %nation% when a town has no nation.
  nonationslug: ''
  
  
regionstyle:
  strokecolor: '#FF0000'
  strokeopacity: '0.8'
  strokeweight: '3'
  fillcolor: '#FF0000'
  fillopacity: '0.35'
  boost: 'false'
  
  # Allowed icon names found here: https://github.com/webbukkit/dynmap/wiki/Using-Markers
  icons:
    homeicon: blueflag
    capitalicon: king
    outposticon: tower
    ruinicon: warning
  
# Optional setting to limit which regions to show, by name - if commented out, all regions are shown.
# To show all regions on a given world, add 'world:<worldname>' to the list.
visibleregions: '[]'
  
# Optional setting to hide specific regions, by name.
# To hide all regions on a given world, add 'world:<worldname>' to the list.
hiddenregions: '[]'
  
  
custstyle:
  customregion1:
    strokeColor: '#00FF00'
    y: 64
  customregion2:
    strokeColor: '#007F00'
    y: 64
    boost: false
  
  
nationstyle:
  NationOfBlue:
    strokeColor: '#0000FF'
    fillColor: '#0000FF'
    boost: false
  _none_:
    homeicon: greenflag
  
version:
  # This is the current version.  Please do not edit.
  version: 1.1.3
  
# Requires Player-Info-Is-Protected enabled in dynmap.
player_visibility:
  
  # Allow all residents of a given town to see one another.
  visibility-by-town: 'true'
  
  # Allow all residents of a given nation to see one another.
  visibility-by-nation: 'true'
  
  
townblock_colours:
  shops:
  
    # Show shop plots with their own fill colour.
    showshops: 'false'
  
    # The colour shops plots are filled with.
    fillcolour: '#0000FF'
  arenas:
  
    # Show arena plots with their own fill colour.
    showarenas: 'false'
  
    # The colour arena plots are filled with.
    fillcolour: '#FF00FF'
  embassies:
  
    # Show embassy plots with their own fill colour.
    showembassies: 'false'
  
    # The colour embassy plots are filled with.
    fillcolour: '#00FFFF'
  wilds:
  
    # Show wilds plots with their own fill colour.
    showwilds: 'false'
  
    # The colour wilds plots are filled with.
    fillcolour: '#00FF00'
  
  
dynamic_colours:
  
  # Use dynamic nation colors, which are set in-game by individual nations (using /t set mapcolor <colour>)
  town_colours: 'true'
  
  # Use dynamic nation colors, which are set in-game by individual nations (using /n set mapcolor <colour>)
  nation_colours: 'true'
# The language file you wish to use
language: english.yml
  
# Chat settings for use with TownyChat.
chat:
  sendlogin: 'true'
  sendquit: 'true'
  format: '&color;2[WEB] %playername%: &color;f%message%'
