#time in seconds
Time: 1800

Invulnerability_message: '&8&l(&a&l!&8&l)&a You are invulnerable to other players for the next 30 minutes!'

NoInvulnerability_message: '&8&l(&c&l!&8&l)&c You are no longer invulnerable to other players!'